<?php
$phrases = [
    "Born to express, not to impress.",
    "Hi there. I joined Linkme. Happy now?",
    "All I do is win, win, win. No matter what 🥇",
    "Too dead to die.",
    "Believer in the power of kindness.",
    "Happiness is homemade 🏠",
    "Making every day count.",
    "Learning, growing, and evolving.",
    "Music lover, foodie, and adventurer ⛰️",
    "On a journey called life.",
    "Living, laughing, and loving.",
    "Dreaming big, one step at a time 🚶🏻",
    "Sharing my thoughts, one post at a time.",
    "Enjoying the simple pleasures of life.",
    "Following my heart wherever it leads.",
    "Living my best life.",
    "Life’s a journey; enjoy the ride.",
    "Embracing the chaos.",
    "Coffee and kindness enthusiast ☕",
    "Living in the moment.",
    "Finding joy in the little moments.",
    "Family first, always.",
    "Turning dreams into reality ☁️",
    "Living, loving, and learning 📖",
    "Making memories and sharing smiles.",
    "Chasing dreams and catching flights.",
    "Living life one day at a time.",
    "Having a zest for life.",
    "Finding inspiration in the ordinary.",
    "Striving for progress, not perfection.",
    "Making life beautiful in my own way.",
    "Just trying to be a better person.",
    "Adventure is out there!",
    "Exploring the beauty of everyday life.",
    "Creating my own sunshine ☀️",
    "Finding joy in the little things.",
    "Positive vibes only.",
    "Spreading love and positivity 🌅",
    "Exploring new horizons.",
    "Happiness is a choice.",
    "Just being proud 💫",
    "Hustle and heart set me apart.",
    "Lost in the pages of life’s adventures.",
    "Exploring the world one post at a time.",
    "In a world of squares, I’m just trying to fit in.",
    "Embracing the chaos with a smile. 😊",
    "Epic moments, tiny captions.",
    "Turning ordinary into extraordinary.",
    "Sunshine mixed with a little hurricane. ☀️🌪️",
    "Less perfection, more authenticity.",
    "Making memories and taking names.",
    "Chasing dreams and catching flights.",
    "Living my story, one post at a time.",
    "Simplicity is the ultimate sophistication."
];
